apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-69-tenant/load-app-0a4dc16b-4541-4af2-9590-fa5a8f9c207f/devfile-sample-python-basic@sha256:67d03ffe45c3b616e37dd017d570265971f35f7b23bbb0719b25182825853a94
        name: my-python
        resources: {}
status: {}
